export const SNIP: Record<string, string> = {
hudHtml: `<!-- Content/UI/hud.html -->
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { margin: 0; background: transparent; }
    .ammo {
      position: fixed; right: 32px; bottom: 24px;
      font: 600 44px/1 ui-monospace, monospace;
      color: #ececf1; text-align: right;
    }
    .ammo small { display: block; font-size: 12px; opacity: .55; }
  </style>
</head>
<body>
  <div class="ammo"><span id="ammo">24</span><small>RESERVE 180</small></div>

  <script>
    // React to Unreal state — no polling, no bridge glue.
    swui.on('Weapon.CurrentAmmo', v => {
      document.getElementById('ammo').textContent = v;
    });
  </script>
</body>
</html>`,

react: `import { useSwuiState, useSwuiEvent } from '@swui/react';

export function AmmoCounter() {
  const ammo   = useSwuiState<number>('Weapon.CurrentAmmo', 30);
  const reload = useSwuiEvent('Weapon.Reload');

  reload.on(() => flash('RELOADING'));

  return <div className="ammo">{ammo}</div>;
}`,

vue: `import { useSwuiState, useSwuiEvent } from '@swui/vue';

const health = useSwuiState('Player.Health', 100);
const reload  = useSwuiEvent('Weapon.Reload');

// Same contract, same GameplayTags —
// only the rendering layer changes.
defineComponent({ template: '<div>{{ health }}</div>' });`,

svelte: `<script>
  import { swuiState, swuiEvent } from '@swui/svelte';

  const spread = swuiState('Weapon.CurrentSpread', 0.3);
  const fired  = swuiEvent('Weapon.OnPlayerFiredShot');

  // A Svelte store backed by the runtime.
  $: gap = 6 + $spread * 42;
</script>

<div class="crosshair" style="--gap: {gap}px"></div>`,

vanilla: `// No framework. No Node. One file.
// Content/UI/hud.html → USwuiDocumentAsset → done.

swui.on('Weapon.CurrentAmmo', v => {
  document.querySelector('#ammo').textContent = v;
});

swui.navigation.onConfirm(() => {
  document.activeElement?.click();
});`,

gen: `// Generated by SWUI 3.0 — do not edit.
// Source of truth: Blueprint graph observation nodes & UScriptStructs.

export interface SwuiState {
  'Player.Health': number;
  'Player.Shield': number;
  'Weapon.CurrentAmmo': number;
  'Weapon.CurrentSpread': number;
  'HUDState.CrosshairMode': 'PRECISE' | 'EXPANDED' | 'SNIPER';
  'Interaction.bCanInteract': boolean;
  'Interaction.Prompt': string;
}

export interface SwuiEvents {
  'Weapon.OnPlayerFiredShot': {
    gunType: string;
    ammoRemaining: number;
    spread: number;
  };
  'Combat.OnHitConfirmed': { damage: number };
  'Weapon.Reload': Record<string, never>;
  'UI.Inventory.UseItem': { itemId: string; slot: number };
}`,

config: `import { defineConfig } from '@swui/cli';

export default defineConfig({
  name: 'MainHUD',
  framework: 'react',
  entry: 'src/main.tsx',
  output: 'Content/UI/dist',
  runtime: {
    layer: 'Level',
    loadBehavior: 'Eager',
    frameRate: 60,
    transparent: true,
  },
});`,

anim: `const spring = swui.animation.createSpring({
  stiffness: 170,
  damping: 26,
  mass: 1.0,
});

swui.state.subscribe('Weapon.CurrentSpread', target => {
  spring.to(target);
});

swui.state.onTick(({ dt }) => {
  crosshair.setSpread(spring.step(dt));
});`,

state: `// Read current state synchronously
const ammo = swui.state.get('Weapon.CurrentAmmo');

// Subscribe to a single field change
swui.state.subscribe('Weapon.CurrentSpread', v => {
  crosshair.setSpread(v);
});

// Propagate a state patch toward Unreal
swui.state.update({ 'UI.MenuVolume': 0.4 });

// React once per frame, to the whole atomic batch
swui.state.onBatch(batch => {
  stats.beginFrame(batch.version);
});

// Runtime tick — engine time, not wall time
swui.state.onTick(({ dt, time, paused }) => {
  if (!paused) world.step(dt);
});`,

events: `// Web → Unreal (structured, tag-routed navigation command)
swui.events.emit('UI.Inventory.UseItem', {
  itemId: 'health_potion',
  slot: 2,
});

// Unreal → Web (reflected delegates with typed payloads)
swui.events.on('Weapon.OnPlayerFiredShot', ({ ammoRemaining }) => {
  ammoEl.textContent = ammoRemaining;
});

// Gamepad-grade navigation, routed by the runtime
swui.events.emitNavigation('confirm');`,

navigation: `swui.navigation.onNavigate(dir => focus.move(dir));
// 'up' | 'down' | 'left' | 'right'

swui.navigation.onConfirm(()  => focus.current().click());
swui.navigation.onCancel(()   => closeDocument());
swui.navigation.onNextTab(()  => tabs.next());
swui.navigation.onPreviousTab(() => tabs.prev());`,

recipe1Bp: `// PlayerController Blueprint / C++ Workflow
// BeginPlay: Load HUD & Bind UI Navigation Handler
DocMgr = GetGameInstance()->GetSubsystem<USwuiDocumentManagerSubsystem>();
DocMgr->LoadDocumentAsset(DA_MainHUD);
DocMgr->ActivateDocument(FName("MainHUD"));

// Toggle Inventory Action (Key: I or Tab)
if (DocMgr->GetDocumentState(FName("Inventory")) == ESwuiDocumentState::Active) {
    DocMgr->DeactivateDocument(FName("Inventory")); // Sleep saves 100% GPU/CPU
    SetShowMouseCursor(false);
    SetInputMode(FInputModeGameOnly());
} else {
    DocMgr->ActivateDocument(FName("Inventory"), 100); // ZOrder: 100 (Modal)
    SetShowMouseCursor(true);
    SetInputMode(FInputModeGameAndUI());
}`,

recipe1Js: `// Inside Content/UI/inventory.html / React Component
function handleUseItem(itemId: string, slot: number) {
  // Emit typed navigation event to Unreal Engine
  window.__SWUI__.send(JSON.stringify({
    type: "navigation",
    tag: "UI.Inventory.UseItem",
    payload: { itemId, slot }
  }));
}

// Esc key closes modal cleanly
window.addEventListener("keydown", (e) => {
  if (e.key === "Escape") {
    window.__SWUI__.send(JSON.stringify({
      type: "navigation",
      tag: "UI.Menu.CloseInventory"
    }));
  }
});`,

recipe2PauseBp: `// Pause Pressed (Escape / Gamepad Start)
// Unreal world freezes, but SWUI continues ticking!
UGameplayStatics::SetGamePaused(GetWorld(), true);

DocMgr = GetGameInstance()->GetSubsystem<USwuiDocumentManagerSubsystem>();
DocMgr->ActivateDocument(FName("PauseMenu"), 200); // Modal Layer

SetShowMouseCursor(true);
SetInputMode(FInputModeUIOnly());

// Note: USwuiDocumentManagerSubsystem implements FTickableGameObject
// with TickableWhenPaused = true, keeping web animations fluid at 60 FPS.`,

recipe2PauseReact: `// React PauseMenuModal.tsx with Page-Aware Cancel
import { useEffect, useState } from "react";
import Swui from "./swui.esm";

type PausePage = "main" | "settings";

export function PauseMenuModal() {
  const [open, setOpen] = useState(false);
  const [page, setPage] = useState<PausePage>("main");

  function handleCancel() {
    if (!open) return;
    if (page === "settings") {
      setPage("main"); // Back to main menu
      return;
    }
    // Main menu cancel -> Resume game
    Swui.emitAction?.("ClosePause");
  }

  useEffect(() => {
    const offOpen   = Swui.onAction("OpenPause", () => { setPage("main"); setOpen(true); });
    const offCancel = Swui.onCancel(handleCancel);
    return () => { offOpen(); offCancel(); };
  }, [open, page]);

  if (!open) return null;
  return (
    <div className="pause-modal">
      {page === "main" ? (
        <nav>
          <button onClick={() => Swui.emitAction?.("ClosePause")}>Continue</button>
          <button onClick={() => setPage("settings")}>Settings</button>
          <button onClick={() => Swui.emitAction?.("QuitGame")}>Quit Game</button>
        </nav>
      ) : (
        <div>
          <button onClick={() => setPage("main")}>← Back</button>
          <h2>Settings</h2>
        </div>
      )}
    </div>
  );
}`,

recipe3Preload: `// C++ Zero-Stutter Level Preloading Workflow
// 1. When entering loading screen or level travel:
USwuiDocumentManagerSubsystem* DocMgr = 
    GetGameInstance()->GetSubsystem<USwuiDocumentManagerSubsystem>();

// CEF offscreen browser instantiates & compiles HTML/JS in background
DocMgr->PreloadDocument(FName("Level02HUD"));

// 2. Once level stream finishes and viewport fades in:
// Document is already rendered to shared texture — instant activation!
DocMgr->ActivateDocument(FName("Level02HUD"));
// 0ms hitch, 0 FPS drop, instant transition`,

recipe4World: `// 3D In-World Mesh Screen: USwui Actor Component
// Add USwui component to your terminal or cockpit actor:
USwui* SwuiComp = CreateDefaultSubobject<USwui>(TEXT("TerminalScreen"));
SwuiComp->DocumentAsset = DA_TerminalScreen;
SwuiComp->RenderMode = ESwuiRenderMode::CpuCompatible; // or GpuAccelerated
SwuiComp->TextureParameterName = FName("UI_Texture");

// The component automatically handles ticking, shared texture upload,
// and binds the rendered UTexture2D directly to your DynamicMaterialInstance!`,

recipe5Nav: `// Gamepad & Focus Navigation (SwuiNavigation)
// Bind Enhanced Input actions directly into SwuiNavigation:
void AMyPlayerController::SetupInputComponent()
{
    Super::SetupInputComponent();
    
    // D-Pad / Thumbstick -> Directional Navigation
    EnhancedInput->BindAction(IA_NavMove, ETriggerEvent::Triggered, 
        this, &AMyPlayerController::HandleNavMove);
        
    // Face Button Bottom (A / Cross) -> Confirm
    EnhancedInput->BindAction(IA_NavConfirm, ETriggerEvent::Started,
        DocMgr, &USwuiDocumentManagerSubsystem::NavigationConfirm);
        
    // Face Button Right (B / Circle) -> Cancel
    EnhancedInput->BindAction(IA_NavCancel, ETriggerEvent::Started,
        DocMgr, &USwuiDocumentManagerSubsystem::NavigationCancel);
}`,

typedNav: `// 1. Code-exposed Navigation Event in C++:
UFUNCTION(meta = (SwuiEvent = "onev.rooms.host"))
void HostRoom(const FString& RoomName, const FString& MapId, bool bIsPublic);

// 2. SWUI Auto-generates typed TypeScript helper:
export const SwuiNavigationEvents = {
  roomsHost(payload: { RoomName: string; MapId: string; bIsPublic: boolean }) {
    Swui.emitNavigationEvent("onev.rooms.host", payload);
  }
};

// 3. Blueprint expands K2Node_SwuiNavigationEvent with typed struct pins!`,

delegatePayload: `// Automatic Delegate Parameter Serialization
// UPROPERTY(BlueprintAssignable) dynamic multicast delegates
// are observed by USwuiDelegateBridge via UObject::ProcessEvent override:
void USwuiDelegateBridge::ProcessEvent(UFunction* Function, void* Parms)
{
    if (Function == HookFunction && SignatureFunction)
    {
        // Iterates SignatureFunction FProperty list and reads values from Parms buffer
        FString JsonPayload = SerializeParametersToJson(SignatureFunction, Parms);
        DispatchJsCustomEvent(DelegateEventName, JsonPayload);
    }
}`,

trcss: `/* Transparent Web UI in SWUI */
body {
  margin: 0;
  background: transparent !important;
}

/* Also ensure bIsTransparent = true on USwuiDocumentAsset */`
}
