export const SNIP: Record<string, string> = {
hudHtml: `<!-- Content/UI/hud.html -->
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { margin: 0; background: transparent; }
    .ammo {
      position: fixed; right: 32px; bottom: 24px;
      font: 600 44px/1 ui-monospace, monospace;
      color: #ececf1; text-align: right;
    }
    .ammo small { display: block; font-size: 12px; opacity: .55; }
  </style>
</head>
<body>
  <div class="ammo"><span id="ammo">24</span><small>RESERVE 180</small></div>

  <script>
    // React to Unreal state — no polling, no bridge glue.
    swui.on('Weapon.CurrentAmmo', v => {
      document.getElementById('ammo').textContent = v;
    });
  </script>
</body>
</html>`,
react: `import { useSwuiState, useSwuiEvent } from '@swui/react';

export function AmmoCounter() {
  const ammo   = useSwuiState<number>('Weapon.CurrentAmmo', 30);
  const reload = useSwuiEvent('Weapon.Reload');

  reload.on(() => flash('RELOADING'));

  return <div className="ammo">{ammo}</div>;
}`,
vue: `import { useSwuiState, useSwuiEvent } from '@swui/vue';

const health = useSwuiState('Player.Health', 100);
const reload  = useSwuiEvent('Weapon.Reload');

// Same contract, same GameplayTags —
// only the rendering layer changes.
defineComponent({ template: '<div>{{ health }}</div>' });`,
svelte: `<script>
  import { swuiState, swuiEvent } from '@swui/svelte';

  const spread = swuiState('Weapon.CurrentSpread', 0.3);
  const fired  = swuiEvent('Weapon.OnPlayerFiredShot');

  // A Svelte store backed by the runtime.
  $: gap = 6 + $spread * 42;
</script>

<div class="crosshair" style="--gap: {gap}px"></div>`,
vanilla: `// No framework. No Node. One file.
// Content/UI/hud.html → USwuiDocumentAsset → done.

swui.on('Weapon.CurrentAmmo', v => {
  document.querySelector('#ammo').textContent = v;
});

swui.navigation.onConfirm(() => {
  document.activeElement?.click();
});`,
gen: `// Generated by SWUI — do not edit.
// Source of truth: Blueprint graph observation nodes.

export interface SwuiState {
  'Player.Health': number;
  'Player.Shield': number;
  'Weapon.CurrentAmmo': number;
  'Weapon.CurrentSpread': number;
  'HUDState.CrosshairMode': 'PRECISE' | 'EXPANDED' | 'SNIPER';
  'Interaction.bCanInteract': boolean;
  'Interaction.Prompt': string;
}

export interface SwuiEvents {
  'Weapon.OnPlayerFiredShot': {
    gunType: string;
    ammoRemaining: number;
    spread: number;
  };
  'Combat.OnHitConfirmed': { damage: number };
  'Weapon.Reload': Record<string, never>;
}`,
config: `import { defineConfig } from '@swui/cli';

export default defineConfig({
  name: 'MainHUD',
  framework: 'react',
  entry: 'src/main.tsx',
  output: 'dist',
  runtime: {
    layer: 'level',
    loadBehavior: 'eager',
    frameRate: 60,
  },
});`,
anim: `const spring = swui.animation.createSpring({
  stiffness: 170,
  damping: 26,
});

swui.state.subscribe('Weapon.CurrentSpread', target => {
  spring.to(target);
});

swui.state.onTick(({ dt }) => {
  crosshair.setSpread(spring.step(dt));
});`,
state: `// Read current state
const ammo = swui.state.get('Weapon.CurrentAmmo');

// Subscribe to a single field
swui.state.subscribe('Weapon.CurrentSpread', v => {
  crosshair.setSpread(v);
});

// Propagate a state patch
swui.state.update({ 'UI.MenuVolume': 0.4 });

// React once per frame, to the whole batch
swui.state.onBatch(batch => {
  stats.beginFrame(batch.version);
});

// Runtime tick — engine time, not wall time
swui.state.onTick(({ dt, time, paused }) => {
  if (!paused) world.step(dt);
});`,
events: `// Web → Unreal (structured, tag-routed)
swui.events.emit('UI.Inventory.UseItem', {
  itemId: 'health_potion',
  slot: 2,
});

// Unreal → Web (reflected events as subscriptions)
swui.events.on('Weapon.OnPlayerFiredShot', ({ ammoRemaining }) => {
  ammoEl.textContent = ammoRemaining;
});

// Gamepad-grade navigation, routed by the runtime
swui.events.emitNavigation('confirm');`,
navigation: `swui.navigation.onNavigate(dir => focus.move(dir));
// up | down | left | right

swui.navigation.onConfirm(()  => focus.current().click());
swui.navigation.onCancel(()   => closeDocument());
swui.navigation.onNextTab(()  => tabs.next());
swui.navigation.onPreviousTab(() => tabs.prev());`,
trcss: `body {
  background: transparent;
}

/* plus: enable transparency
   on the USwuiDocumentAsset */`
}

